### ISSUE TITLE
Enhance JOB command documentation on gtmroutines env var vs $zroutines isv

### ISSUE THREAD

**Issue by nars1** [YottaDB/YottaDBdoc#109]
The JOB command has the following documentation.
```
https://docs.yottadb.com/ProgrammersGuide/commands.html#the-job-environment

The JOB Environment
When the JOB is forked, UNIX creates the environment for the new process by copying the environment of the process issuing the JOB command and making a few minor modifications. By default, the standard input is assigned to the null device, the standard output is assigned to routinename.mjo, and the standard error is assigned to routinename.mje.
```
It would help to highlight that if the $gtmroutines environment variable content is different from the $zroutines ISV (because $zroutines was changed once the jobbing process started), the jobbed off process will inherit $gtmroutines but not $zroutines. This means that if the M entryref (LABEL^PROGRAM) that is being jobbed off can be found only through $zroutines, but not through $gtmroutines, the jobbed off process will encounter a ZLINKFILE error (due to not being able to find the M program through $gtmroutines) whereas the program would be found just fine in the jobbing process and this would be difficult to debug.

Additionally, it would help to enhance the ZLINKFILE error message documentation (in the Messages & Recovery doc) to highlight the JOB command subtlety.

**Comment by ranjani789** [comment]
https://github.com/YottaDB/YottaDBdoc/commit/f4cabfbe988a6ee91787eeee94111e882bfba225 #111
