### ISSUE TITLE
Add clarification to description of zcompile in Programmers Guide

### ISSUE THREAD

**Issue by ksbhaskar** [YottaDB/YottaDBdoc#54]
https://groups.google.com/d/topic/hardhats/N1UXW94ve24/discussion shows a potential source of confusion in the zcompile description. Changing _one or more filenames_ to _one or more relative or absolute paths to files_ would solve the issue.

**Comment by ranjani789** [comment]
Changed description at https://docs.yottadb.com/ProgrammersGuide/commands.html#zcompile
