### ISSUE TITLE
Remove contents of Appendix F of the Admin and Ops

### ISSUE THREAD

**Issue by ksbhaskar** [YottaDB/YottaDBdoc#63]
This appendix describes the gtmpcat tool, proprietary software that FIS has not publicly released. The contents of the appendix should be removed and replaced with text along the lines of “This Appendix intentionally left blank” (so that references in the rest of the document to following appendices do not need correction).

**Comment by ranjani789** [comment]
Removed all references to gtmpcat in the Admin and Ops document + removed Appendix F

https://docs.yottadb.com/AdminOpsGuide/index.html
