### ISSUE TITLE
Need to document line editing keystrokes

### ISSUE THREAD

**Issue by ksbhaskar** [YottaDB/YottaDBdoc#72]
The information at http://tinco.pair.com/bhaskar/gtm/doc/articles/GTM_M_Read_Editing_for_Unix.html#id4216713 should be in the Programmers Guide.

**Comment by ranjani789** [comment]
M Read Editing Section is now in the Prgrammer's Guide.

https://docs.yottadb.com/ProgrammersGuide/ioproc.html#m-read-editing
